In [2]:
import numpy
n = numpy.arange(27)

In [3]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
type(n)

numpy.ndarray

In [5]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [7]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
[[123,12,123,12,33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [10]:
m = numpy.asarray([[123,12,123,12,33],[],[]])

In [11]:
print(m)

[list([123, 12, 123, 12, 33]) list([]) list([])]


In [12]:
type(m)

numpy.ndarray

In [16]:
import cv2


ModuleNotFoundError: No module named 'cv2'